// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cart.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCart = `-- name: CreateCart :one
INSERT INTO carts (id, created_at, updated_at, customer_id, total_price, total_discounted_price, total_quantity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, customer_id, total_price, total_discounted_price, total_quantity
`

type CreateCartParams struct {
	ID                   string           `json:"id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	CustomerID           string           `json:"customer_id"`
	TotalPrice           float64          `json:"total_price"`
	TotalDiscountedPrice pgtype.Float8    `json:"total_discounted_price"`
	TotalQuantity        int32            `json:"total_quantity"`
}

// Carts
func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CustomerID,
		arg.TotalPrice,
		arg.TotalDiscountedPrice,
		arg.TotalQuantity,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.TotalPrice,
		&i.TotalDiscountedPrice,
		&i.TotalQuantity,
	)
	return i, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (id, created_at, updated_at, product_item_id, quantity, cart_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, product_item_id, quantity, cart_id
`

type CreateCartItemParams struct {
	ID            string           `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProductItemID string           `json:"product_item_id"`
	Quantity      int32            `json:"quantity"`
	CartID        string           `json:"cart_id"`
}

// Cart Items
func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, createCartItem,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ProductItemID,
		arg.Quantity,
		arg.CartID,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductItemID,
		&i.Quantity,
		&i.CartID,
	)
	return i, err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts
WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCartItem, id)
	return err
}

const getCart = `-- name: GetCart :one
SELECT id, created_at, updated_at, customer_id, total_price, total_discounted_price, total_quantity FROM carts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCart(ctx context.Context, id string) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.TotalPrice,
		&i.TotalDiscountedPrice,
		&i.TotalQuantity,
	)
	return i, err
}

const getCartByCustomer = `-- name: GetCartByCustomer :one
SELECT id, created_at, updated_at, customer_id, total_price, total_discounted_price, total_quantity FROM carts
WHERE customer_id = $1 LIMIT 1
`

func (q *Queries) GetCartByCustomer(ctx context.Context, customerID string) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByCustomer, customerID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.TotalPrice,
		&i.TotalDiscountedPrice,
		&i.TotalQuantity,
	)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, created_at, updated_at, product_item_id, quantity, cart_id FROM cart_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCartItem(ctx context.Context, id string) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductItemID,
		&i.Quantity,
		&i.CartID,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, created_at, updated_at, product_item_id, quantity, cart_id FROM cart_items
WHERE cart_id = $1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type ListCartItemsParams struct {
	CartID string `json:"cart_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListCartItems(ctx context.Context, arg ListCartItemsParams) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, listCartItems, arg.CartID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductItemID,
			&i.Quantity,
			&i.CartID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCart = `-- name: UpdateCart :one
UPDATE carts
SET total_price = $2, total_discounted_price = $3, total_quantity = $4, updated_at = $5
WHERE id = $1
RETURNING id, created_at, updated_at, customer_id, total_price, total_discounted_price, total_quantity
`

type UpdateCartParams struct {
	ID                   string           `json:"id"`
	TotalPrice           float64          `json:"total_price"`
	TotalDiscountedPrice pgtype.Float8    `json:"total_discounted_price"`
	TotalQuantity        int32            `json:"total_quantity"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateCart(ctx context.Context, arg UpdateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCart,
		arg.ID,
		arg.TotalPrice,
		arg.TotalDiscountedPrice,
		arg.TotalQuantity,
		arg.UpdatedAt,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.TotalPrice,
		&i.TotalDiscountedPrice,
		&i.TotalQuantity,
	)
	return i, err
}

const updateCartItem = `-- name: UpdateCartItem :one
UPDATE cart_items
SET quantity = $2, updated_at = $3
WHERE id = $1
RETURNING id, created_at, updated_at, product_item_id, quantity, cart_id
`

type UpdateCartItemParams struct {
	ID        string           `json:"id"`
	Quantity  int32            `json:"quantity"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItem, arg.ID, arg.Quantity, arg.UpdatedAt)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductItemID,
		&i.Quantity,
		&i.CartID,
	)
	return i, err
}
