// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID           string           `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	AddressLine1 string           `json:"address_line_1"`
	AddressLine2 pgtype.Text      `json:"address_line_2"`
	City         string           `json:"city"`
	Pincode      string           `json:"pincode"`
	CountryID    string           `json:"country_id"`
}

type Cart struct {
	ID                   string           `json:"id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	CustomerID           string           `json:"customer_id"`
	TotalPrice           float64          `json:"total_price"`
	TotalDiscountedPrice pgtype.Float8    `json:"total_discounted_price"`
	TotalQuantity        int32            `json:"total_quantity"`
}

type CartItem struct {
	ID            string           `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProductItemID string           `json:"product_item_id"`
	Quantity      int32            `json:"quantity"`
	CartID        string           `json:"cart_id"`
}

type Category struct {
	ID               string           `json:"id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	StoreID          string           `json:"store_id"`
	ParentCategoryID pgtype.Text      `json:"parent_category_id"`
	Variants         json.RawMessage  `json:"variants"`
}

type Country struct {
	ID        string           `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Country   string           `json:"country"`
}

type Order struct {
	ID            string           `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	OrderNumber   string           `json:"order_number"`
	PaymentStatus string           `json:"payment_status"`
	OrderStatus   string           `json:"order_status"`
	StoreID       string           `json:"store_id"`
	CustomerID    string           `json:"customer_id"`
}

type OrderItem struct {
	ID            string           `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProductItemID string           `json:"product_item_id"`
	Quantity      int32            `json:"quantity"`
	OrderID       string           `json:"order_id"`
}

type Product struct {
	ID           string           `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Rating       pgtype.Float8    `json:"rating"`
	IsFeatured   pgtype.Bool      `json:"is_featured"`
	IsArchived   pgtype.Bool      `json:"is_archived"`
	HasVariants  pgtype.Bool      `json:"has_variants"`
	CategoryID   string           `json:"category_id"`
	StoreID      string           `json:"store_id"`
	CategoryName string           `json:"category_name"`
	Variants     json.RawMessage  `json:"variants"`
}

type ProductImage struct {
	ID            string           `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProductItemID string           `json:"product_item_id"`
	ImageUrl      string           `json:"image_url"`
}

type ProductItem struct {
	ID              string           `json:"id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	ProductID       string           `json:"product_id"`
	Sku             string           `json:"sku"`
	Quantity        int32            `json:"quantity"`
	Price           float64          `json:"price"`
	DiscountedPrice pgtype.Float8    `json:"discounted_price"`
	CostPrice       pgtype.Float8    `json:"cost_price"`
	Options         json.RawMessage  `json:"options"`
}

type Store struct {
	ID          string           `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	UserID      string           `json:"user_id"`
}

type User struct {
	ID        string           `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      string           `json:"role"`
	StoreID   pgtype.Text      `json:"store_id"`
}

type Variant struct {
	ID          string           `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Options     json.RawMessage  `json:"options"`
	StoreID     string           `json:"store_id"`
}
