// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (id, created_at, updated_at, title, product_variant_id, display_order, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, title, product_variant_id, display_order, image_url
`

type CreateImageParams struct {
	ID               string           `json:"id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	Title            string           `json:"title"`
	ProductVariantID pgtype.Text      `json:"product_variant_id"`
	DisplayOrder     int32            `json:"display_order"`
	ImageUrl         string           `json:"image_url"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.ProductVariantID,
		arg.DisplayOrder,
		arg.ImageUrl,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ProductVariantID,
		&i.DisplayOrder,
		&i.ImageUrl,
	)
	return i, err
}

const updateImage = `-- name: UpdateImage :one
UPDATE images
SET title = $2, image_url = $3, display_order = $4, updated_at = $5
WHERE id = $1
RETURNING id, created_at, updated_at, title, product_variant_id, display_order, image_url
`

type UpdateImageParams struct {
	ID           string           `json:"id"`
	Title        string           `json:"title"`
	ImageUrl     string           `json:"image_url"`
	DisplayOrder int32            `json:"display_order"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage,
		arg.ID,
		arg.Title,
		arg.ImageUrl,
		arg.DisplayOrder,
		arg.UpdatedAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ProductVariantID,
		&i.DisplayOrder,
		&i.ImageUrl,
	)
	return i, err
}
